### ISSUE TITLE
How to compile and execute?

### ISSUE THREAD

**Issue by miguelriemoliveira** [vitoruapt/pariaula12B#1]
We need a **Compilation** and **How to run** sections on the README, I have created it already, can you fill them in?

**Comment by miguelriemoliveira** [comment]
Hi  @vitoruapt , I created the sections for you to write in.

Compilation is here: https://github.com/vitoruapt/pariaula12B#compilation

and Execution [here](https://github.com/vitoruapt/pariaula12B#execution)

**Comment by miguelriemoliveira** [comment]
Hi @vitoruapt ,

I added some proposals for those sections, please review and validate.

You may close the issue when its done.

**Comment by vitoruapt** [comment]
Compilation instructions: common rules of cmake based projects taking advantage of the out-source building. Create a build directory, change into ir, run cmake indicating the path of the CMakeLists.txt file, and perform the building tasks like "make". Suggested steps:
-- mkdir build
-- cd build
-- cmake ..
-- make
