### ISSUE TITLE
Which functions should be implemented by the students?

### ISSUE THREAD

**Issue by miguelriemoliveira** [vitoruapt/pariaula12B#2]
Hi @vitoruapt ,

which functions should be implemented by the students? Drawing each of the entities? But some of them are already being drawn ...

Where are these functions and how to do them (I don't know how to do them, but I can be the github support and you say how)?

Is there anything else the students have to do? Because these are parallel functionalities, there really are no dependency issues between them, which is the best way to get them to collaborate (to force them )

**Comment by vitoruapt** [comment]
In file auxcallbacks.c create/complete the following functions:

void pari_draw_starpolygon(GdkEvent *event);
void pari_draw_freehandpolygon(GdkEvent *event);
void pari_draw_circularcrown(GdkEvent *event);
void pari_draw_text(GdkEvent *event);
